import { type FormEvent, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { bandeiraCartaoApi } from '../lib/bandeira-cartao-api.ts';
import type { BandeiraCartao, BandeiraCartaoInput } from '../types/bandeira-cartao.ts';
import { useCrudResource } from '../hooks/use-crud-resource.ts';
import { SimpleCrudPage } from '../components/simple-crud-page.tsx';
import { Input } from '../components/ui/input.tsx';
import { Label } from '../components/ui/label.tsx';
const sortItems = (items: BandeiraCartao[]) => [...items].sort((a, b) => a.description.localeCompare(b.description));
export function CardBrands() { const { t } = useTranslation(); const [description, setDescription] = useState(''); const resource = useCrudResource<BandeiraCartao, BandeiraCartaoInput>({ api: bandeiraCartaoApi, loadErrorMessage: t('cardBrands.loadError'), createdMessage: t('cardBrands.created'), updatedMessage: t('cardBrands.updated'), deletedMessage: t('cardBrands.deleted'), sortItems }); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (await resource.save({ description })) setDescription(''); }; const openEdit = (item: BandeiraCartao) => { setDescription(item.description); resource.openEdit(item); }; return <SimpleCrudPage columnsClassName="grid-cols-[minmax(0,1fr)_auto]" section={t('cardBrands.section')} title={t('cardBrands.title')} newLabel={t('cardBrands.new')} addLabel={t('cardBrands.add')} listDescription={t('cardBrands.listTitle')} columnHeader={t('cardBrands.column')} items={resource.items} editingItem={resource.editingItem} deletingItem={resource.deletingItem} isFormOpen={resource.isFormOpen} isLoading={resource.isLoading} error={resource.error} formError={resource.formError} emptyLabel={t('cardBrands.empty')} editLabel={t('cardBrands.edit')} deleteLabel={t('cardBrands.deleteLabel', { description: resource.deletingItem?.description ?? '' })} deleteTitle={t('cardBrands.deleteTitle')} deleteConfirmation={t('cardBrands.deleteConfirmation', { description: resource.deletingItem?.description ?? '' })} onOpenCreate={() => { setDescription(''); resource.openCreate(); }} onOpenEdit={openEdit} onCloseForm={resource.closeForm} onSetDeleting={resource.setDeletingItem} onRemove={resource.remove} onSubmit={submit} renderForm={() => <div className="space-y-2"><Label htmlFor="card-brand-description" required>{t('cardBrands.description')}</Label><Input id="card-brand-description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder={t('cardBrands.descriptionPlaceholder')} required autoFocus hasError={Boolean(resource.formError)} /></div>} renderRow={(item, actions) => <div key={item.id} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-b border-slate-100 px-5 py-3 text-sm text-slate-700 last:border-b-0"><span className="min-w-0 truncate font-medium">{item.description}</span>{actions}</div>} />; }
