import { type FormEvent, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { instituicaoBancariaApi } from '../lib/instituicao-bancaria-api.ts';
import type { InstituicaoBancaria, InstituicaoBancariaInput } from '../types/instituicao-bancaria.ts';
import { useCrudResource } from '../hooks/use-crud-resource.ts';
import { SimpleCrudPage } from '../components/simple-crud-page.tsx';
import { Input } from '../components/ui/input.tsx';
import { Label } from '../components/ui/label.tsx';
const sortItems = (items: InstituicaoBancaria[]) => [...items].sort((a, b) => a.name.localeCompare(b.name));
export function BankInstitutions() { const { t } = useTranslation(); const [name, setName] = useState(''); const resource = useCrudResource<InstituicaoBancaria, InstituicaoBancariaInput>({ api: instituicaoBancariaApi, loadErrorMessage: t('bankInstitutions.loadError'), createdMessage: t('bankInstitutions.created'), updatedMessage: t('bankInstitutions.updated'), deletedMessage: t('bankInstitutions.deleted'), sortItems }); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (await resource.save({ name })) setName(''); }; const openEdit = (item: InstituicaoBancaria) => { setName(item.name); resource.openEdit(item); }; return <SimpleCrudPage section={t('bankInstitutions.section')} title={t('bankInstitutions.title')} newLabel={t('bankInstitutions.new')} addLabel={t('bankInstitutions.add')} listDescription={t('bankInstitutions.listTitle')} columnHeader={t('bankInstitutions.column')} items={resource.items} editingItem={resource.editingItem} deletingItem={resource.deletingItem} isFormOpen={resource.isFormOpen} isLoading={resource.isLoading} error={resource.error} formError={resource.formError} emptyLabel={t('bankInstitutions.empty')} editLabel={t('bankInstitutions.edit')} deleteLabel={t('bankInstitutions.deleteLabel', { name: resource.deletingItem?.name ?? '' })} deleteTitle={t('bankInstitutions.deleteTitle')} deleteConfirmation={t('bankInstitutions.deleteConfirmation', { name: resource.deletingItem?.name ?? '' })} onOpenCreate={() => { setName(''); resource.openCreate(); }} onOpenEdit={openEdit} onCloseForm={resource.closeForm} onSetDeleting={resource.setDeletingItem} onRemove={resource.remove} onSubmit={submit} renderForm={() => <div className="space-y-2"><Label htmlFor="bank-institution-name" required>{t('bankInstitutions.name')}</Label><Input id="bank-institution-name" value={name} onChange={(event) => setName(event.target.value)} placeholder={t('bankInstitutions.namePlaceholder')} required autoFocus hasError={Boolean(resource.formError)} /></div>} renderRow={(item, actions) => <div key={item.id} className="flex items-center gap-3 border-b border-slate-100 px-5 py-3 text-sm text-slate-700 last:border-b-0"><span className="min-w-0 flex-1 truncate font-medium">{item.name}</span>{actions}</div>} />; }
